#!/bin/bash

# The parameter $1 is the backup directory location
# which will be compressed afterward
backup_dir=$1/apps/dokuwiki
mkdir -p $backup_dir

# Backup sources & data
sudo cp -a /var/www/dokuwiki/. $backup_dir/sources

# Copy Nginx and YunoHost parameters to make the script "standalone"
sudo cp -a /etc/yunohost/apps/dokuwiki/. $backup_dir/yunohost
domain=$(sudo yunohost app setting dokuwiki domain)
sudo cp -a /etc/nginx/conf.d/$domain.d/dokuwiki.conf $backup_dir/nginx.conf