#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

source .fonctions
# Source app helpers
source /usr/share/yunohost/helpers

# This is a multi-instance app, meaning it can be installed several times independently
# The id of the app as stated in the manifest is available as $YNH_APP_ID
# The instance number is available as $YNH_APP_INSTANCE_NUMBER (equals "1", "2", ...)
# The app instance name is available as $YNH_APP_INSTANCE_NAME
#    - the first time the app is installed, YNH_APP_INSTANCE_NAME = ynhexample
#    - the second time the app is installed, YNH_APP_INSTANCE_NAME = ynhexample__2
#    - ynhexample__{N} for the subsequent installations, with N=3,4, ...
# The app instance name is probably what you are interested the most, since this is
# guaranteed to be unique. This is a good unique identifier to define installation path,
# db names, ...
app=$YNH_APP_INSTANCE_NAME

# Retrieve app settings
domain=$(ynh_app_setting_get $app domain)
path=$(ynh_app_setting_get $app path)
admin=$(ynh_app_setting_get $app admin)
is_public=$(ynh_app_setting_get $app is_public)
multisite=$(ynh_app_setting_get $app multisite)

# Remove trailing slash to path
path=${path%/}
#force location to be / or /foo
location=${path:-/}

# admin default value, if not set
if [ -z "$admin" ];
then
	admin=$(sudo yunohost user list | grep 'username' -m1 | awk '{print $2}')
	sudo ynh_app_setting_set $app is_public -v "$is_public"
fi

# Modify dokuwiki conf
sed -i "s@YNH_ADMIN_USER@$admin@g" ../conf/dokuwiki.php

# Copy files to the right place
final_path=/var/www/$app
sudo mkdir -p $final_path

# Get source
SETUP_SOURCE

sudo cp ../conf/dokuwiki.php $final_path/conf

# Do not override ACL configuration file
if [ ! -f "$final_path/conf/acl.auth.php" ]; then
	sudo cp ../conf/acl.auth.php $final_path/conf
fi

# Remove upgrade notification
# See https://www.dokuwiki.org/update_check
sudo touch $final_path/doku.php

# Remove deleted files
# See https://www.dokuwiki.org/install:unused_files
if [ -f "../sources/data/deleted.files" ]; then
	grep -Ev '^($|#)' ../sources/data/deleted.files | xargs -I {} sudo rm -vrf $final_path/{}
fi

# Change owner for all plugins
sudo chmod -R 755 $final_path/lib/plugins

# Update all plugins
for name_plugin in $(sudo -s cat $final_path/lib/plugins/*/plugin.info.txt | grep url | awk -F':' '{print $3}');
do
		# Get a official plugin for dokuwiki, not update a no-official
		sudo wget -nv --quiet "https://github.com/splitbrain/dokuwiki-plugin-${name_plugin}/zipball/master" -O "${name_plugin}.zip" -o /dev/null || true
		if [ -s "${name_plugin}.zip" ]; then
			sudo unzip ${name_plugin}.zip
			sudo cp -a splitbrain-dokuwiki-plugin-${name_plugin}*/. "${final_path}/lib/plugins/${name_plugin}/"
		fi
done

# Files owned by www-data can just read
# sudo find $final_path -type f -print0 | xargs -0 sudo chmod 0644
# sudo find $final_path -type d -print0 | xargs -0 sudo chmod 0755
sudo chown -R www-data: $final_path

# except for conf, data, some data subfolders, and lib/plugin, where www-data must have write permissions
if [ -d "${final_path}/data/media" ]; then
	sudo chown -R www-data:root $final_path/{data/attic,data/cache,data/index,data/locks,data/media*,data/meta,data/pages,data/tmp}
fi
sudo chown -R www-data:root $final_path/{conf,data,lib/plugins,lib/tpl}
sudo chmod -R 700 $final_path/conf
sudo chmod -R 700 $final_path/data
sudo chmod -R 700 $final_path/lib/plugins
sudo chmod -R 700 $final_path/lib/tpl

# Modify Nginx configuration file and copy it to Nginx conf directory
sudo sed -i "s@__PATHTOCHANGE__@$path@g" /etc/nginx/conf.d/$domain.d/$app.conf
sudo sed -i "s@__FINALPATH__@$final_path@g" /etc/nginx/conf.d/$domain.d/$app.conf
sudo sed -i "s@__NAMETOCHANGE__@$app@g" /etc/nginx/conf.d/$domain.d/$app.conf

if [ "$is_public" = "Yes" ];
then
	sudo sed -i "s@#--PRIVATE--@@g" /etc/nginx/conf.d/$domain.d/$app.conf
fi

# Create the php-fpm pool config
POOL_FPM

# Setup SSOwat
ynh_app_setting_set "$app" is_public "$is_public"
if [ "$is_public" = "Yes" ];
then
  ynh_app_setting_set "$app" unprotected_uris "/"
fi

sudo systemctl reload php5-fpm
sudo systemctl reload nginx
sudo yunohost app ssowatconf